runtime: nodejs18

handlers:
  # Serve static files with appropriate cache settings
  - url: /(.*\.(gif|png|jpg|ico|txt|js|css|woff|woff2|ttf|svg))
    static_files: out/\1
    upload: out/.*\.(gif|png|jpg|ico|txt|js|css|woff|woff2|ttf|svg)
    secure: always
    redirect_http_response_code: 301
    http_headers:
      Cache-Control: "public, max-age=31536000"

  # Serve HTML files with shorter cache time
  - url: /(.*\.html)
    static_files: out/\1
    upload: out/.*\.html
    secure: always
    redirect_http_response_code: 301
    http_headers:
      Cache-Control: "public, max-age=3600"

  # Serve all other files as index.html for SPA navigation
  - url: /.*
    static_files: out/index.html
    upload: out/index.html
    secure: always
    redirect_http_response_code: 301
    http_headers:
      Cache-Control: "public, max-age=3600"

env_variables:
  NODE_ENV: "production"
