import { Bitcoin, Shield, TrendingUp, Server, Network, Cpu, Link, Lightbulb } from 'lucide-react';
import type { Section, Difficulty, LearningModule } from '../types/learning';

export const bitcoinModules: LearningModule[] = [
  {
    id: 'fundamentals',
    title: 'Bitcoin Fundamentals',
    description: 'Learn the core concepts of Bitcoin',
    difficulty: 'Beginner',
    icon: Bitcoin,
    locked: false,
    sections: [
      {
        id: 'what-is-bitcoin',
        title: 'What is Bitcoin?',
        description: 'Introduction to Bitcoin',
        difficulty: 'Beginner',
        checkboxCount: 1,
      },
      {
        id: 'the-blockchain',
        title: 'The Blockchain',
        description: 'Understanding blockchain technology',
        difficulty: 'Beginner',
        checkboxCount: 1,
      },
      {
        id: 'private-keys-wallets',
        title: 'Private Keys & Wallets',
        description: 'Managing Bitcoin securely',
        difficulty: 'Beginner',
        checkboxCount: 1,
      },
      {
        id: 'making-transactions',
        title: 'Making Transactions',
        description: 'Send and receive Bitcoin',
        difficulty: 'Beginner',
        checkboxCount: 1,
      },
    ],
  },
  {
    id: 'economics',
    title: 'Bitcoin Economics',
    description: "Understand Bitcoin's economic principles",
    difficulty: 'Intermediate',
    icon: TrendingUp,
    locked: true,
    sections: [
      {
        id: 'bitcoin-economics',
        title: 'Bitcoin Economics',
        description: 'Economic principles of Bitcoin',
        difficulty: 'Intermediate',
        checkboxCount: 1,
      },
      {
        id: 'monetary-policy',
        title: 'Monetary Policy',
        description: "Bitcoin's monetary system",
        difficulty: 'Intermediate',
        checkboxCount: 1,
      },
      {
        id: 'game-theory',
        title: 'Game Theory',
        description: 'Incentives and game theory',
        difficulty: 'Intermediate',
        checkboxCount: 1,
      },
      {
        id: 'market-dynamics',
        title: 'Market Dynamics',
        description: 'Understanding Bitcoin markets',
        difficulty: 'Intermediate',
        checkboxCount: 1,
      },
      {
        id: 'economic-impact',
        title: 'Economic Impact',
        description: "Bitcoin's impact on the economy",
        difficulty: 'Intermediate',
        checkboxCount: 1,
      },
    ],
  },
  {
    id: 'technical',
    title: 'Technical Deep Dive',
    description: 'Advanced technical concepts',
    difficulty: 'Advanced',
    icon: Cpu,
    locked: true,
    sections: [
      {
        id: 'script-language',
        title: 'Script Language',
        description: "Bitcoin's scripting system",
        difficulty: 'Advanced',
        checkboxCount: 1,
      },
      {
        id: 'mining-consensus',
        title: 'Mining & Consensus',
        description: 'How Bitcoin achieves consensus',
        difficulty: 'Advanced',
        checkboxCount: 1,
      },
      {
        id: 'network-architecture',
        title: 'Network Architecture',
        description: "Bitcoin's P2P network",
        difficulty: 'Advanced',
        checkboxCount: 1,
      },
      {
        id: 'protocol-updates',
        title: 'Protocol Updates',
        description: 'Bitcoin improvement process',
        difficulty: 'Advanced',
        checkboxCount: 1,
      },
    ],
  },
];

export const lightningModules: LearningModule[] = [
  {
    id: 'lightning-fundamentals',
    title: 'Lightning Fundamentals',
    description: 'Learn the core concepts of the Lightning Network',
    difficulty: 'Beginner',
    icon: Lightbulb,
    locked: false,
    sections: [
      {
        id: 'what-is-lightning',
        title: 'What is Lightning?',
        description: 'Introduction to the Lightning Network',
        difficulty: 'Beginner',
        checkboxCount: 1,
      },
      {
        id: 'how-lightning-works',
        title: 'How Lightning Works',
        description: 'Understanding the technical foundations',
        difficulty: 'Beginner',
        checkboxCount: 1,
      },
      {
        id: 'payment-channels',
        title: 'Payment Channels',
        description: 'Learn about Lightning payment channels',
        difficulty: 'Beginner',
        checkboxCount: 1,
      },
      {
        id: 'network-topology',
        title: 'Network Topology',
        description: 'Understanding network structure',
        difficulty: 'Beginner',
        checkboxCount: 1,
      },
      {
        id: 'htlc',
        title: 'Hash Time-Locked Contracts',
        description: 'Understanding HTLCs',
        difficulty: 'Beginner',
        checkboxCount: 1,
      },
      {
        id: 'onion-routing',
        title: 'Onion Routing',
        description: 'Privacy and routing in Lightning',
        difficulty: 'Beginner',
        checkboxCount: 1,
      },
    ],
  },
  {
    id: 'lightning-node-operations',
    title: 'Node Operations',
    description: 'Learn how to run and manage a Lightning node',
    difficulty: 'Intermediate',
    icon: Server,
    locked: true,
    sections: [
      {
        id: 'node-installation',
        title: 'Node Installation',
        description: 'Installing Lightning node software',
        difficulty: 'Intermediate',
        checkboxCount: 1,
      },
      {
        id: 'node-setup',
        title: 'Node Setup',
        description: 'Setting up your Lightning node',
        difficulty: 'Intermediate',
        checkboxCount: 1,
      },
      {
        id: 'basic-configuration',
        title: 'Basic Configuration',
        description: 'Configuring basic node settings',
        difficulty: 'Intermediate',
        checkboxCount: 1,
      },
      {
        id: 'channel-management',
        title: 'Channel Management',
        description: 'Managing Lightning channels effectively',
        difficulty: 'Intermediate',
        checkboxCount: 1,
      },
      {
        id: 'routing',
        title: 'Routing',
        description: 'Understanding Lightning payment routing',
        difficulty: 'Intermediate',
        checkboxCount: 1,
      },
      {
        id: 'monitoring',
        title: 'Monitoring',
        description: 'Monitoring node health and performance',
        difficulty: 'Intermediate',
        checkboxCount: 1,
      },
      {
        id: 'maintenance-tasks',
        title: 'Maintenance Tasks',
        description: 'Performing routine node maintenance',
        difficulty: 'Intermediate',
        checkboxCount: 1,
      },
      {
        id: 'backups',
        title: 'Backups',
        description: 'Backing up your node and channel data',
        difficulty: 'Intermediate',
        checkboxCount: 1,
      },
      {
        id: 'security-setup',
        title: 'Security Setup',
        description: 'Securing your Lightning node',
        difficulty: 'Intermediate',
        checkboxCount: 1,
      },
    ],
  },
  {
    id: 'lightning-channel-management',
    title: 'Channel Management',
    description: 'Master Lightning Network channel operations',
    difficulty: 'Intermediate',
    icon: Link,
    locked: true,
    sections: [
      {
        id: 'opening-channels',
        title: 'Opening Channels',
        description: 'Learn to open Lightning channels',
        difficulty: 'Intermediate',
        checkboxCount: 1,
      },
      {
        id: 'channel-capacity',
        title: 'Channel Capacity',
        description: 'Understanding channel capacity',
        difficulty: 'Intermediate',
        checkboxCount: 1,
      },
      {
        id: 'channel-balancing',
        title: 'Channel Balancing',
        description: 'Balancing channel liquidity',
        difficulty: 'Intermediate',
        checkboxCount: 1,
      },
      {
        id: 'closing-channels',
        title: 'Closing Channels',
        description: 'Properly closing channels',
        difficulty: 'Intermediate',
        checkboxCount: 1,
      },
    ],
  },
  {
    id: 'lightning-routing-operations',
    title: 'Routing Operations',
    description: 'Learn about routing payments in the Lightning Network',
    difficulty: 'Advanced',
    icon: Network,
    locked: true,
    sections: [
      {
        id: 'path-finding',
        title: 'Path Finding',
        description: 'Understanding payment routing',
        difficulty: 'Advanced',
        checkboxCount: 1,
      },
      {
        id: 'fee-management',
        title: 'Fee Management',
        description: 'Managing routing fees',
        difficulty: 'Advanced',
        checkboxCount: 1,
      },
      {
        id: 'payment-forwarding',
        title: 'Payment Forwarding',
        description: 'Forwarding Lightning payments',
        difficulty: 'Advanced',
        checkboxCount: 1,
      },
      {
        id: 'route-optimization',
        title: 'Route Optimization',
        description: 'Optimizing payment routes',
        difficulty: 'Advanced',
        checkboxCount: 1,
      },
    ],
  },
  {
    id: 'lightning-security',
    title: 'Security',
    description: 'Understand Lightning Network security',
    difficulty: 'Advanced',
    icon: Shield,
    locked: true,
    sections: [
      {
        id: 'node-security',
        title: 'Node Security',
        description: 'Securing your Lightning node',
        difficulty: 'Advanced',
        checkboxCount: 1,
      },
      {
        id: 'channel-security',
        title: 'Channel Security',
        description: 'Securing Lightning channels',
        difficulty: 'Advanced',
        checkboxCount: 1,
      },
      {
        id: 'network-security',
        title: 'Network Security',
        description: 'Network-level security',
        difficulty: 'Advanced',
        checkboxCount: 1,
      },
      {
        id: 'key-management',
        title: 'Key Management',
        description: 'Managing Lightning keys',
        difficulty: 'Advanced',
        checkboxCount: 1,
      },
    ],
  },
  {
    id: 'lightning-advanced',
    title: 'Advanced Concepts',
    description: 'Master advanced Lightning Network concepts',
    difficulty: 'Advanced',
    icon: Cpu,
    locked: true,
    sections: [
      {
        id: 'htlc-deep-dive',
        title: 'HTLC Deep Dive',
        description: 'Advanced understanding of HTLCs',
        difficulty: 'Advanced',
        checkboxCount: 1,
      },
      {
        id: 'multipath',
        title: 'Multipath Payments',
        description: 'Understanding multipath payments',
        difficulty: 'Advanced',
        checkboxCount: 1,
      },
      {
        id: 'submarine',
        title: 'Submarine Swaps',
        description: 'Understanding submarine swaps',
        difficulty: 'Advanced',
        checkboxCount: 1,
      },
      {
        id: 'watchtowers',
        title: 'Watchtowers',
        description: 'Understanding Lightning watchtowers',
        difficulty: 'Advanced',
        checkboxCount: 1,
      },
    ],
  },
];
